//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by iFlyWebUi4.rc

#define IDS_APP_TITLE			103

#define IDR_MAINFRAME			128
#define IDD_IFLYWEBUI4_DIALOG	102
#define IDD_ABOUTBOX			103
#define IDM_ABOUT				104
#define IDM_EXIT				105
#define IDI_IFLYWEBUI4			107
#define IDI_SMALL				108
#define IDC_IFLYWEBUI4			109
#define IDC_MYICON				2
#ifndef IDC_STATIC
#define IDC_STATIC				-1
#endif
// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					130
#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_COMMAND_VALUE		32771
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		110
#endif
#endif

// Main Window buttons etc

#define IDC_MAIN_STATUS (WM_APP+10)
#define IDC_BUTTON		(WM_APP+11)
#define IDC_MAIN_EDIT	(WM_APP+15)

//interface status

#define ID_INTERFACE_OK              (WM_APP+20)
#define ID_INTERFACE_NOT_OK          (WM_APP+21)
#define ID_THREAD_OK				 (WM_APP+22)
#define ID_THREAD_EXIT               (WM_APP+23)
#define ID_INTERFACE_RESTART         (WM_APP+23)

//simulator status
#define ID_FSUIPC_NOT_OK             (WM_APP+30)
#define ID_IFLY_SDK_NOT_OK           (WM_APP+31)
#define ID_IFLY_SDK2_NOT_OK          (WM_APP+32)
#define ID_IFLY_NOT_OK               (WM_APP+33)
#define ID_FS_IFLY_OK                (WM_APP+34)
#define ID_SIMCONNECT_NOT_OK		 (WM_APP+35)

//Wt toolkit server status
#define ID_WITTY_OK					 (WM_APP+36)
#define ID_WITTY_NOT_OK				 (WM_APP+37)

//webui buttons
#define ID_WEBUI_BUTTON_GROUND_POWER	(WM_APP+40)
#define ID_WEBUI_BUTTON_GROUND_AIR		(WM_APP+41)

#define ID_WEBUI_BUTTON_DOOR1		(WM_APP+42)
#define ID_WEBUI_BUTTON_DOOR2		(WM_APP+43)
#define ID_WEBUI_BUTTON_DOOR3		(WM_APP+44)

#define ID_WEBUI_BUTTON_PUSHBACK1		(WM_APP+45)
#define ID_WEBUI_BUTTON_PUSHBACK2		(WM_APP+46)
#define ID_WEBUI_BUTTON_PUSHBACK3		(WM_APP+47)
#define ID_WEBUI_BUTTON_PUSHBACK4		(WM_APP+48)
#define ID_WEBUI_BUTTON_RESET_OOOI		(WM_APP+49)

#define ID_WEBUI_TIMER_TIMEOUT			(WM_APP+60)

// Flight states for oooi function
#define FLIGHTSTATE_PREFLIGHT			(WM_APP+70)
#define FLIGHTSTATE_PB_OR_TAXI_OUT		(WM_APP+71)
#define FLIGHTSTATE_ON_AIR				(WM_APP+72)
#define FLIGHTSTATE_TAXI_IN				(WM_APP+73)
#define FLIGHTSTATE_POSTFLIGHT			(WM_APP+74)
#define FLIGHTSTATE_COMPLETED			(WM_APP+75)

//GSX buttons

#define ID_WEBUI_BUTTON_VIRTUAL_KEY_0	(WM_APP+80)
#define ID_WEBUI_BUTTON_VIRTUAL_KEY_1	(WM_APP+81)
#define ID_WEBUI_BUTTON_VIRTUAL_KEY_2	(WM_APP+82)
#define ID_WEBUI_BUTTON_VIRTUAL_KEY_3	(WM_APP+83)
#define ID_WEBUI_BUTTON_VIRTUAL_KEY_4	(WM_APP+84)
#define ID_WEBUI_BUTTON_VIRTUAL_KEY_5	(WM_APP+85)
#define ID_WEBUI_BUTTON_VIRTUAL_KEY_6	(WM_APP+86)
#define ID_WEBUI_BUTTON_VIRTUAL_KEY_7	(WM_APP+87)
#define ID_WEBUI_BUTTON_VIRTUAL_KEY_8	(WM_APP+88)
#define ID_WEBUI_BUTTON_VIRTUAL_KEY_9	(WM_APP+89)
#define ID_WEBUI_BUTTON_VIRTUAL_KEY_F10	(WM_APP+90)
#define ID_WEBUI_BUTTON_VIRTUAL_KEY_F11	(WM_APP+91)
#define ID_WEBUI_BUTTON_VIRTUAL_KEY_F12	(WM_APP+92)
